30 May 2022 21:17:40,843 ERROR   Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: alfresco-content-common
30 May 2022 21:17:40,843 ERROR   Error running template command. Exit Value = 1.
30 May 2022 21:17:40,844 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-elasticsearch-connector 
30 May 2022 21:17:40,844 ERROR   Exception rendering template for alfresco-elasticsearch-connector:0.1.0 : Error running template command. Exit Value = 1.
30 May 2022 21:17:40,844 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-elasticsearch-connector:0.1.0 : Error running template command. Exit Value = 1.
30 May 2022 21:19:08,908 ERROR   Chart alfresco-content-services:5.3.0-A172 printed successfully with the refresh option. See the prior errors that occured without the refresh option to understand why refresh was needed.
30 May 2022 21:22:43,608 ERROR   Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: alfresco-content-common
30 May 2022 21:22:43,608 ERROR   Error running template command. Exit Value = 1.
30 May 2022 21:22:43,608 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-elasticsearch-connector 
30 May 2022 21:22:43,608 ERROR   Exception rendering template for alfresco-elasticsearch-connector:0.1.0 : Error running template command. Exit Value = 1.
30 May 2022 21:22:43,608 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-elasticsearch-connector:0.1.0 : Error running template command. Exit Value = 1.
30 May 2022 21:29:54,495 ERROR   Chart alfresco-content-services:5.3.0-A171 printed successfully with the refresh option. See the prior errors that occured without the refresh option to understand why refresh was needed.
30 May 2022 21:39:12,804 ERROR   Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: common
30 May 2022 21:39:12,804 ERROR   Error running template command. Exit Value = 1.
30 May 2022 21:39:12,804 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-search 
30 May 2022 21:39:12,804 ERROR   Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
30 May 2022 21:39:12,804 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-search:1.0.4 : Error running template command. Exit Value = 1.
30 May 2022 21:40:17,789 ERROR   Chart alfresco-content-services:5.2.0 printed successfully with the refresh option. See the prior errors that occured without the refresh option to understand why refresh was needed.
30 May 2022 21:47:01,837 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
30 May 2022 21:47:01,837 ERROR   
30 May 2022 21:47:01,837 ERROR   Use --debug flag to render out invalid YAML
30 May 2022 21:47:01,837 ERROR   Error running template command. Exit Value = 1.
30 May 2022 21:47:01,837 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-dmn-service 
30 May 2022 21:47:01,837 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
30 May 2022 21:47:01,837 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
30 May 2022 21:48:25,373 ERROR   Error: YAML parse error on alfresco-dmn-service/charts/alfresco-dmn-service/templates/deployment.yaml: error converting YAML to JSON: yaml: line 59: could not find expected ':'
30 May 2022 21:48:25,373 ERROR   
30 May 2022 21:48:25,373 ERROR   Use --debug flag to render out invalid YAML
30 May 2022 21:48:25,373 ERROR   Error running template command. Exit Value = 1.
30 May 2022 21:48:25,373 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,insightzeppelin.enabled=true,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true"  template alfresco-dmn-service 
30 May 2022 21:48:25,373 ERROR   Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
30 May 2022 21:48:25,373 ERROR   Error resolving chart dependencies: Exception rendering template for alfresco-dmn-service:0.1.0 : Error running template command. Exit Value = 1.
30 May 2022 21:48:25,373 ERROR   Chart alfresco-dmn-service:0.1.0 failed to print even with the refresh option.
30 May 2022 21:55:42,843 ERROR   Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

30 May 2022 21:55:42,843 ERROR   Error resolving chart dependencies: Exception rendering template for process-services-infrastructure:0.1.1 : while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 72, column 10:
    metadata:	
             ^

30 May 2022 21:57:46,441 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.4351188869612129013/process-services-infrastructure/charts/alfresco-infrastructure.  Exit code: 1.  Possibly you cannot access one of your remote charts repos.
30 May 2022 21:57:46,442 ERROR   Chart process-services-infrastructure:0.1.1 failed to print even with the refresh option.
