02 Jun 2022 04:06:29,790 ERROR   Error: YAML parse error on kuberhealthy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: mapping values are not allowed in this context
02 Jun 2022 04:06:29,790 ERROR   
02 Jun 2022 04:06:29,790 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:06:29,790 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:06:29,791 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template kuberhealthy 
02 Jun 2022 04:06:29,791 ERROR   Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
02 Jun 2022 04:06:29,791 ERROR   Error resolving chart dependencies: Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
02 Jun 2022 04:06:31,303 ERROR   Error: YAML parse error on kuberhealthy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: mapping values are not allowed in this context
02 Jun 2022 04:06:31,303 ERROR   
02 Jun 2022 04:06:31,303 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:06:31,303 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:06:31,303 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template kuberhealthy 
02 Jun 2022 04:06:31,304 ERROR   Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
02 Jun 2022 04:06:31,304 ERROR   Error resolving chart dependencies: Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
02 Jun 2022 04:06:31,305 ERROR   Chart kuberhealthy:1.2.5 failed to print even with the refresh option.
02 Jun 2022 04:12:27,611 ERROR   WARNING: This chart is deprecated
02 Jun 2022 04:12:27,611 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
02 Jun 2022 04:12:27,611 ERROR   
02 Jun 2022 04:12:27,611 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:12:27,611 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:12:27,611 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
02 Jun 2022 04:12:27,611 ERROR   Exception rendering template for mission-control:0.4.4 : Error running template command. Exit Value = 1.
02 Jun 2022 04:12:27,611 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.4 : Error running template command. Exit Value = 1.
02 Jun 2022 04:12:31,814 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.4827740629241847806/mission-control.  Exit code: 1.  Possibly you cannot access one of your remote charts repos.
02 Jun 2022 04:12:31,815 ERROR   Chart mission-control:0.4.4 failed to print even with the refresh option.
02 Jun 2022 04:12:33,346 ERROR   WARNING: This chart is deprecated
02 Jun 2022 04:12:33,346 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
02 Jun 2022 04:12:33,346 ERROR   
02 Jun 2022 04:12:33,346 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:12:33,346 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:12:33,346 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
02 Jun 2022 04:12:33,346 ERROR   Exception rendering template for mission-control:0.4.3 : Error running template command. Exit Value = 1.
02 Jun 2022 04:12:33,346 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.3 : Error running template command. Exit Value = 1.
02 Jun 2022 04:12:37,537 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.4406158704394216380/mission-control.  Exit code: 1.  Possibly you cannot access one of your remote charts repos.
02 Jun 2022 04:12:37,538 ERROR   Chart mission-control:0.4.3 failed to print even with the refresh option.
02 Jun 2022 04:12:39,053 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
02 Jun 2022 04:12:39,054 ERROR   
02 Jun 2022 04:12:39,054 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:12:39,054 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:12:39,054 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
02 Jun 2022 04:12:39,054 ERROR   Exception rendering template for mission-control:0.4.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:12:39,054 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:12:43,233 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.3867381654344780584/mission-control.  Exit code: 1.  Possibly you cannot access one of your remote charts repos.
02 Jun 2022 04:12:43,234 ERROR   Chart mission-control:0.4.2 failed to print even with the refresh option.
02 Jun 2022 04:13:07,841 ERROR   Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context
02 Jun 2022 04:13:07,841 ERROR   
02 Jun 2022 04:13:07,841 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:13:07,841 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:13:07,841 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mongodb-replicaset 
02 Jun 2022 04:13:07,841 ERROR   Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:13:07,841 ERROR   Error resolving chart dependencies: Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:13:09,373 ERROR   Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context
02 Jun 2022 04:13:09,374 ERROR   
02 Jun 2022 04:13:09,374 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:13:09,374 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:13:09,374 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mongodb-replicaset 
02 Jun 2022 04:13:09,374 ERROR   Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:13:09,374 ERROR   Error resolving chart dependencies: Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:13:09,374 ERROR   Chart mongodb-replicaset:3.17.0 failed to print even with the refresh option.
02 Jun 2022 04:14:14,845 ERROR   Error: template: mysqldump/templates/configmap.yaml:49:10: executing "mysqldump/templates/configmap.yaml" at <(.Values.persistence.enabled) or (.Values.persistentVolumeClaim)>: can't give argument to non-function .Values.persistence.enabled
02 Jun 2022 04:14:14,845 ERROR   
02 Jun 2022 04:14:14,845 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:14:14,845 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:14:14,845 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mysqldump 
02 Jun 2022 04:14:14,845 ERROR   Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:14:14,845 ERROR   Error resolving chart dependencies: Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:14:16,387 ERROR   Error: template: mysqldump/templates/configmap.yaml:49:10: executing "mysqldump/templates/configmap.yaml" at <(.Values.persistence.enabled) or (.Values.persistentVolumeClaim)>: can't give argument to non-function .Values.persistence.enabled
02 Jun 2022 04:14:16,387 ERROR   
02 Jun 2022 04:14:16,387 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:14:16,387 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:14:16,387 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mysqldump 
02 Jun 2022 04:14:16,387 ERROR   Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:14:16,387 ERROR   Error resolving chart dependencies: Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:14:16,387 ERROR   Chart mysqldump:2.6.0 failed to print even with the refresh option.
02 Jun 2022 04:20:37,730 ERROR   Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

02 Jun 2022 04:20:37,730 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

02 Jun 2022 04:20:39,257 ERROR   Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

02 Jun 2022 04:20:39,257 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

02 Jun 2022 04:20:39,257 ERROR   Chart pgadmin:1.2.3 failed to print even with the refresh option.
02 Jun 2022 04:20:40,772 ERROR   Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

02 Jun 2022 04:20:40,773 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

02 Jun 2022 04:20:42,282 ERROR   Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

02 Jun 2022 04:20:42,282 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

02 Jun 2022 04:20:42,282 ERROR   Chart pgadmin:1.2.2 failed to print even with the refresh option.
02 Jun 2022 04:29:45,076 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.2.puml
02 Jun 2022 04:29:49,803 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.1.puml
02 Jun 2022 04:29:54,370 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.0.puml
02 Jun 2022 04:32:15,588 ERROR   WARNING: This chart is deprecated
02 Jun 2022 04:32:15,588 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
02 Jun 2022 04:32:15,588 ERROR   
02 Jun 2022 04:32:15,588 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:32:15,588 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:32:15,588 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
02 Jun 2022 04:32:15,588 ERROR   Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:15,588 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:17,117 ERROR   WARNING: This chart is deprecated
02 Jun 2022 04:32:17,118 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
02 Jun 2022 04:32:17,118 ERROR   
02 Jun 2022 04:32:17,118 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:32:17,118 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:32:17,118 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
02 Jun 2022 04:32:17,118 ERROR   Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:17,118 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:17,118 ERROR   Chart signalsciences:2.0.2 failed to print even with the refresh option.
02 Jun 2022 04:32:18,592 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
02 Jun 2022 04:32:18,592 ERROR   
02 Jun 2022 04:32:18,592 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:32:18,592 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:32:18,593 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
02 Jun 2022 04:32:18,593 ERROR   Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:18,593 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:20,111 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
02 Jun 2022 04:32:20,111 ERROR   
02 Jun 2022 04:32:20,112 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:32:20,112 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:32:20,112 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
02 Jun 2022 04:32:20,112 ERROR   Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:20,112 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:20,112 ERROR   Chart signalsciences:2.0.1 failed to print even with the refresh option.
02 Jun 2022 04:32:21,628 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
02 Jun 2022 04:32:21,628 ERROR   
02 Jun 2022 04:32:21,628 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:32:21,628 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:32:21,628 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
02 Jun 2022 04:32:21,628 ERROR   Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:21,628 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:23,141 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
02 Jun 2022 04:32:23,141 ERROR   
02 Jun 2022 04:32:23,141 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:32:23,141 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:32:23,141 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
02 Jun 2022 04:32:23,141 ERROR   Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:23,141 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:32:23,142 ERROR   Chart signalsciences:2.0.0 failed to print even with the refresh option.
02 Jun 2022 04:33:48,992 ERROR   WARNING: This chart is deprecated
02 Jun 2022 04:33:48,992 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
02 Jun 2022 04:33:48,992 ERROR   
02 Jun 2022 04:33:48,992 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:33:48,992 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:33:48,992 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
02 Jun 2022 04:33:48,992 ERROR   Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
02 Jun 2022 04:33:48,992 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
02 Jun 2022 04:34:01,979 ERROR   WARNING: This chart is deprecated
02 Jun 2022 04:34:01,979 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
02 Jun 2022 04:34:01,979 ERROR   
02 Jun 2022 04:34:01,979 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:34:01,979 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:34:01,979 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
02 Jun 2022 04:34:01,979 ERROR   Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
02 Jun 2022 04:34:01,979 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
02 Jun 2022 04:34:01,980 ERROR   Chart spinnaker:2.2.6 failed to print even with the refresh option.
02 Jun 2022 04:34:03,646 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
02 Jun 2022 04:34:03,646 ERROR   
02 Jun 2022 04:34:03,646 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:34:03,646 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:34:03,646 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
02 Jun 2022 04:34:03,646 ERROR   Exception rendering template for spinnaker:2.2.3 : Error running template command. Exit Value = 1.
02 Jun 2022 04:34:03,646 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.3 : Error running template command. Exit Value = 1.
02 Jun 2022 04:34:07,951 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.3160799586852586858/spinnaker.  Exit code: 1.  Possibly you cannot access one of your remote charts repos.
02 Jun 2022 04:34:07,952 ERROR   Chart spinnaker:2.2.3 failed to print even with the refresh option.
02 Jun 2022 04:34:09,611 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
02 Jun 2022 04:34:09,611 ERROR   
02 Jun 2022 04:34:09,611 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:34:09,611 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:34:09,611 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
02 Jun 2022 04:34:09,611 ERROR   Exception rendering template for spinnaker:2.2.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:34:09,611 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:34:13,884 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.8188563696987701309/spinnaker.  Exit code: 1.  Possibly you cannot access one of your remote charts repos.
02 Jun 2022 04:34:13,885 ERROR   Chart spinnaker:2.2.2 failed to print even with the refresh option.
02 Jun 2022 04:36:13,591 ERROR   WARNING: This chart is deprecated
02 Jun 2022 04:36:13,591 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
02 Jun 2022 04:36:13,591 ERROR   
02 Jun 2022 04:36:13,591 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:36:13,591 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:36:13,591 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
02 Jun 2022 04:36:13,591 ERROR   Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:13,591 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:15,135 ERROR   WARNING: This chart is deprecated
02 Jun 2022 04:36:15,135 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
02 Jun 2022 04:36:15,135 ERROR   
02 Jun 2022 04:36:15,135 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:36:15,135 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:36:15,135 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
02 Jun 2022 04:36:15,135 ERROR   Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:15,136 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:15,136 ERROR   Chart sumokube:1.0.2 failed to print even with the refresh option.
02 Jun 2022 04:36:16,677 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
02 Jun 2022 04:36:16,677 ERROR   
02 Jun 2022 04:36:16,678 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:36:16,678 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:36:16,678 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
02 Jun 2022 04:36:16,678 ERROR   Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:16,678 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:18,212 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
02 Jun 2022 04:36:18,212 ERROR   
02 Jun 2022 04:36:18,212 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:36:18,212 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:36:18,212 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
02 Jun 2022 04:36:18,213 ERROR   Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:18,213 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:18,213 ERROR   Chart sumokube:1.0.1 failed to print even with the refresh option.
02 Jun 2022 04:36:19,759 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
02 Jun 2022 04:36:19,759 ERROR   
02 Jun 2022 04:36:19,759 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:36:19,759 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:36:19,759 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
02 Jun 2022 04:36:19,759 ERROR   Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:19,759 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:21,368 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
02 Jun 2022 04:36:21,368 ERROR   
02 Jun 2022 04:36:21,368 ERROR   Use --debug flag to render out invalid YAML
02 Jun 2022 04:36:21,368 ERROR   Error running template command. Exit Value = 1.
02 Jun 2022 04:36:21,368 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
02 Jun 2022 04:36:21,369 ERROR   Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:21,369 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
02 Jun 2022 04:36:21,369 ERROR   Chart sumokube:1.0.0 failed to print even with the refresh option.
