15 Jun 2022 23:04:50,765 ERROR   Error: YAML parse error on kuberhealthy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: mapping values are not allowed in this context
15 Jun 2022 23:04:50,765 ERROR   
15 Jun 2022 23:04:50,765 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:04:50,766 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:04:50,766 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template kuberhealthy 
15 Jun 2022 23:04:50,766 ERROR   Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
15 Jun 2022 23:04:50,767 ERROR   Error resolving chart dependencies: Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
15 Jun 2022 23:04:51,865 ERROR   Error: YAML parse error on kuberhealthy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: mapping values are not allowed in this context
15 Jun 2022 23:04:51,865 ERROR   
15 Jun 2022 23:04:51,865 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:04:51,865 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:04:51,865 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template kuberhealthy 
15 Jun 2022 23:04:51,865 ERROR   Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
15 Jun 2022 23:04:51,865 ERROR   Error resolving chart dependencies: Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
15 Jun 2022 23:04:51,867 ERROR   Chart kuberhealthy:1.2.5 failed to print even with the refresh option.
15 Jun 2022 23:09:20,229 ERROR   WARNING: This chart is deprecated
15 Jun 2022 23:09:20,230 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
15 Jun 2022 23:09:20,230 ERROR   
15 Jun 2022 23:09:20,230 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:09:20,230 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:09:20,230 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
15 Jun 2022 23:09:20,230 ERROR   Exception rendering template for mission-control:0.4.4 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:20,230 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.4 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:23,436 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.2863552218990088657/mission-control. Exit code: 1. Possibly you cannot access one of your remote charts repos.
15 Jun 2022 23:09:23,436 ERROR   Chart mission-control:0.4.4 failed to print even with the refresh option.
15 Jun 2022 23:09:24,667 ERROR   WARNING: This chart is deprecated
15 Jun 2022 23:09:24,667 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
15 Jun 2022 23:09:24,667 ERROR   
15 Jun 2022 23:09:24,667 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:09:24,667 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:09:24,667 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
15 Jun 2022 23:09:24,667 ERROR   Exception rendering template for mission-control:0.4.3 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:24,667 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.3 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:27,875 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.6446213563869905809/mission-control. Exit code: 1. Possibly you cannot access one of your remote charts repos.
15 Jun 2022 23:09:27,876 ERROR   Chart mission-control:0.4.3 failed to print even with the refresh option.
15 Jun 2022 23:09:29,120 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
15 Jun 2022 23:09:29,120 ERROR   
15 Jun 2022 23:09:29,120 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:09:29,120 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:09:29,120 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
15 Jun 2022 23:09:29,120 ERROR   Exception rendering template for mission-control:0.4.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:29,120 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:32,338 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.13886898852177094537/mission-control. Exit code: 1. Possibly you cannot access one of your remote charts repos.
15 Jun 2022 23:09:32,338 ERROR   Chart mission-control:0.4.2 failed to print even with the refresh option.
15 Jun 2022 23:09:50,885 ERROR   Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context
15 Jun 2022 23:09:50,885 ERROR   
15 Jun 2022 23:09:50,885 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:09:50,885 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:09:50,885 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mongodb-replicaset 
15 Jun 2022 23:09:50,885 ERROR   Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:50,885 ERROR   Error resolving chart dependencies: Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:52,011 ERROR   Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context
15 Jun 2022 23:09:52,011 ERROR   
15 Jun 2022 23:09:52,011 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:09:52,011 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:09:52,011 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mongodb-replicaset 
15 Jun 2022 23:09:52,011 ERROR   Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:52,011 ERROR   Error resolving chart dependencies: Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:09:52,012 ERROR   Chart mongodb-replicaset:3.17.0 failed to print even with the refresh option.
15 Jun 2022 23:10:41,971 ERROR   Error: template: mysqldump/templates/configmap.yaml:49:10: executing "mysqldump/templates/configmap.yaml" at <(.Values.persistence.enabled) or (.Values.persistentVolumeClaim)>: can't give argument to non-function .Values.persistence.enabled
15 Jun 2022 23:10:41,971 ERROR   
15 Jun 2022 23:10:41,971 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:10:41,971 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:10:41,971 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mysqldump 
15 Jun 2022 23:10:41,971 ERROR   Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:10:41,971 ERROR   Error resolving chart dependencies: Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:10:43,111 ERROR   Error: template: mysqldump/templates/configmap.yaml:49:10: executing "mysqldump/templates/configmap.yaml" at <(.Values.persistence.enabled) or (.Values.persistentVolumeClaim)>: can't give argument to non-function .Values.persistence.enabled
15 Jun 2022 23:10:43,111 ERROR   
15 Jun 2022 23:10:43,111 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:10:43,111 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:10:43,111 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mysqldump 
15 Jun 2022 23:10:43,111 ERROR   Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:10:43,112 ERROR   Error resolving chart dependencies: Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:10:43,112 ERROR   Chart mysqldump:2.6.0 failed to print even with the refresh option.
15 Jun 2022 23:15:38,721 ERROR   Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

15 Jun 2022 23:15:38,721 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

15 Jun 2022 23:15:39,881 ERROR   Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

15 Jun 2022 23:15:39,881 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

15 Jun 2022 23:15:39,881 ERROR   Chart pgadmin:1.2.3 failed to print even with the refresh option.
15 Jun 2022 23:15:41,026 ERROR   Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

15 Jun 2022 23:15:41,027 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

15 Jun 2022 23:15:42,163 ERROR   Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

15 Jun 2022 23:15:42,163 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

15 Jun 2022 23:15:42,164 ERROR   Chart pgadmin:1.2.2 failed to print even with the refresh option.
15 Jun 2022 23:22:37,716 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.2.puml
15 Jun 2022 23:22:41,467 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.1.puml
15 Jun 2022 23:22:44,798 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.0.puml
15 Jun 2022 23:24:29,324 ERROR   WARNING: This chart is deprecated
15 Jun 2022 23:24:29,324 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
15 Jun 2022 23:24:29,324 ERROR   
15 Jun 2022 23:24:29,324 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:24:29,324 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:24:29,324 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
15 Jun 2022 23:24:29,324 ERROR   Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:29,325 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:30,418 ERROR   WARNING: This chart is deprecated
15 Jun 2022 23:24:30,418 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
15 Jun 2022 23:24:30,418 ERROR   
15 Jun 2022 23:24:30,418 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:24:30,418 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:24:30,418 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
15 Jun 2022 23:24:30,418 ERROR   Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:30,418 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:30,419 ERROR   Chart signalsciences:2.0.2 failed to print even with the refresh option.
15 Jun 2022 23:24:31,564 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
15 Jun 2022 23:24:31,564 ERROR   
15 Jun 2022 23:24:31,564 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:24:31,565 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:24:31,565 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
15 Jun 2022 23:24:31,565 ERROR   Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:31,565 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:32,680 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
15 Jun 2022 23:24:32,680 ERROR   
15 Jun 2022 23:24:32,680 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:24:32,680 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:24:32,680 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
15 Jun 2022 23:24:32,680 ERROR   Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:32,680 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:32,681 ERROR   Chart signalsciences:2.0.1 failed to print even with the refresh option.
15 Jun 2022 23:24:33,787 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
15 Jun 2022 23:24:33,787 ERROR   
15 Jun 2022 23:24:33,787 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:24:33,787 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:24:33,787 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
15 Jun 2022 23:24:33,788 ERROR   Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:33,788 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:34,863 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
15 Jun 2022 23:24:34,863 ERROR   
15 Jun 2022 23:24:34,863 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:24:34,863 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:24:34,864 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
15 Jun 2022 23:24:34,864 ERROR   Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:34,864 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:24:34,864 ERROR   Chart signalsciences:2.0.0 failed to print even with the refresh option.
15 Jun 2022 23:25:38,403 ERROR   WARNING: This chart is deprecated
15 Jun 2022 23:25:38,403 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
15 Jun 2022 23:25:38,403 ERROR   
15 Jun 2022 23:25:38,403 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:25:38,403 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:25:38,404 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
15 Jun 2022 23:25:38,404 ERROR   Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
15 Jun 2022 23:25:38,404 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
15 Jun 2022 23:25:50,824 ERROR   WARNING: This chart is deprecated
15 Jun 2022 23:25:50,824 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
15 Jun 2022 23:25:50,824 ERROR   
15 Jun 2022 23:25:50,824 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:25:50,824 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:25:50,824 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
15 Jun 2022 23:25:50,824 ERROR   Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
15 Jun 2022 23:25:50,824 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
15 Jun 2022 23:25:50,825 ERROR   Chart spinnaker:2.2.6 failed to print even with the refresh option.
15 Jun 2022 23:25:52,194 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
15 Jun 2022 23:25:52,194 ERROR   
15 Jun 2022 23:25:52,194 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:25:52,195 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:25:52,195 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
15 Jun 2022 23:25:52,195 ERROR   Exception rendering template for spinnaker:2.2.3 : Error running template command. Exit Value = 1.
15 Jun 2022 23:25:52,195 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.3 : Error running template command. Exit Value = 1.
15 Jun 2022 23:25:55,508 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.6687440247535004193/spinnaker. Exit code: 1. Possibly you cannot access one of your remote charts repos.
15 Jun 2022 23:25:55,508 ERROR   Chart spinnaker:2.2.3 failed to print even with the refresh option.
15 Jun 2022 23:25:56,798 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
15 Jun 2022 23:25:56,798 ERROR   
15 Jun 2022 23:25:56,798 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:25:56,798 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:25:56,798 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
15 Jun 2022 23:25:56,798 ERROR   Exception rendering template for spinnaker:2.2.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:25:56,798 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:26:00,079 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.12682754435543260507/spinnaker. Exit code: 1. Possibly you cannot access one of your remote charts repos.
15 Jun 2022 23:26:00,080 ERROR   Chart spinnaker:2.2.2 failed to print even with the refresh option.
15 Jun 2022 23:27:33,746 ERROR   WARNING: This chart is deprecated
15 Jun 2022 23:27:33,746 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
15 Jun 2022 23:27:33,746 ERROR   
15 Jun 2022 23:27:33,746 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:27:33,746 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:27:33,746 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
15 Jun 2022 23:27:33,746 ERROR   Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:33,746 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:34,853 ERROR   WARNING: This chart is deprecated
15 Jun 2022 23:27:34,853 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
15 Jun 2022 23:27:34,853 ERROR   
15 Jun 2022 23:27:34,853 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:27:34,853 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:27:34,853 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
15 Jun 2022 23:27:34,854 ERROR   Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:34,854 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:34,854 ERROR   Chart sumokube:1.0.2 failed to print even with the refresh option.
15 Jun 2022 23:27:36,013 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
15 Jun 2022 23:27:36,013 ERROR   
15 Jun 2022 23:27:36,013 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:27:36,013 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:27:36,013 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
15 Jun 2022 23:27:36,013 ERROR   Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:36,013 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:37,148 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
15 Jun 2022 23:27:37,148 ERROR   
15 Jun 2022 23:27:37,148 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:27:37,148 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:27:37,148 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
15 Jun 2022 23:27:37,148 ERROR   Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:37,148 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:37,148 ERROR   Chart sumokube:1.0.1 failed to print even with the refresh option.
15 Jun 2022 23:27:38,320 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
15 Jun 2022 23:27:38,320 ERROR   
15 Jun 2022 23:27:38,320 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:27:38,320 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:27:38,320 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
15 Jun 2022 23:27:38,320 ERROR   Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:38,320 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:39,450 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
15 Jun 2022 23:27:39,450 ERROR   
15 Jun 2022 23:27:39,450 ERROR   Use --debug flag to render out invalid YAML
15 Jun 2022 23:27:39,451 ERROR   Error running template command. Exit Value = 1.
15 Jun 2022 23:27:39,451 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
15 Jun 2022 23:27:39,451 ERROR   Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:39,451 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
15 Jun 2022 23:27:39,451 ERROR   Chart sumokube:1.0.0 failed to print even with the refresh option.
