12 Aug 2022 02:28:08,845 ERROR   Error: YAML parse error on kuberhealthy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: mapping values are not allowed in this context
12 Aug 2022 02:28:08,845 ERROR   
12 Aug 2022 02:28:08,845 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:28:08,845 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:28:08,846 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template kuberhealthy 
12 Aug 2022 02:28:08,846 ERROR   Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
12 Aug 2022 02:28:08,846 ERROR   Error resolving chart dependencies: Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
12 Aug 2022 02:28:09,988 ERROR   Error: YAML parse error on kuberhealthy/templates/deployment.yaml: error converting YAML to JSON: yaml: line 41: mapping values are not allowed in this context
12 Aug 2022 02:28:09,988 ERROR   
12 Aug 2022 02:28:09,988 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:28:09,988 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:28:09,988 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template kuberhealthy 
12 Aug 2022 02:28:09,988 ERROR   Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
12 Aug 2022 02:28:09,988 ERROR   Error resolving chart dependencies: Exception rendering template for kuberhealthy:1.2.5 : Error running template command. Exit Value = 1.
12 Aug 2022 02:28:09,990 ERROR   Chart kuberhealthy:1.2.5 failed to print even with the refresh option.
12 Aug 2022 02:32:48,021 ERROR   WARNING: This chart is deprecated
12 Aug 2022 02:32:48,021 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
12 Aug 2022 02:32:48,021 ERROR   
12 Aug 2022 02:32:48,021 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:32:48,021 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:32:48,021 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
12 Aug 2022 02:32:48,021 ERROR   Exception rendering template for mission-control:0.4.4 : Error running template command. Exit Value = 1.
12 Aug 2022 02:32:48,021 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.4 : Error running template command. Exit Value = 1.
12 Aug 2022 02:32:51,873 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.1288518016605038626/mission-control. Exit code: 1. Possibly you cannot access one of your remote charts repos.
12 Aug 2022 02:32:51,873 ERROR   Chart mission-control:0.4.4 failed to print even with the refresh option.
12 Aug 2022 02:32:53,101 ERROR   WARNING: This chart is deprecated
12 Aug 2022 02:32:53,101 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
12 Aug 2022 02:32:53,101 ERROR   
12 Aug 2022 02:32:53,101 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:32:53,101 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:32:53,101 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
12 Aug 2022 02:32:53,101 ERROR   Exception rendering template for mission-control:0.4.3 : Error running template command. Exit Value = 1.
12 Aug 2022 02:32:53,101 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.3 : Error running template command. Exit Value = 1.
12 Aug 2022 02:32:56,305 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.6814817253808042041/mission-control. Exit code: 1. Possibly you cannot access one of your remote charts repos.
12 Aug 2022 02:32:56,306 ERROR   Chart mission-control:0.4.3 failed to print even with the refresh option.
12 Aug 2022 02:32:57,527 ERROR   Error: execution error at (mission-control/templates/mission-control-certs.yaml:21:30): A valid .Values.jfmcTruststore entry required!
12 Aug 2022 02:32:57,527 ERROR   
12 Aug 2022 02:32:57,527 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:32:57,527 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:32:57,527 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mission-control 
12 Aug 2022 02:32:57,528 ERROR   Exception rendering template for mission-control:0.4.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:32:57,528 ERROR   Error resolving chart dependencies: Exception rendering template for mission-control:0.4.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:33:00,719 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.7057960001056097011/mission-control. Exit code: 1. Possibly you cannot access one of your remote charts repos.
12 Aug 2022 02:33:00,719 ERROR   Chart mission-control:0.4.2 failed to print even with the refresh option.
12 Aug 2022 02:33:19,713 ERROR   Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context
12 Aug 2022 02:33:19,713 ERROR   
12 Aug 2022 02:33:19,713 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:33:19,713 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:33:19,713 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mongodb-replicaset 
12 Aug 2022 02:33:19,713 ERROR   Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:33:19,714 ERROR   Error resolving chart dependencies: Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:33:20,895 ERROR   Error: YAML parse error on mongodb-replicaset/templates/mongodb-statefulset.yaml: error converting YAML to JSON: yaml: line 123: mapping values are not allowed in this context
12 Aug 2022 02:33:20,895 ERROR   
12 Aug 2022 02:33:20,895 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:33:20,895 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:33:20,895 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mongodb-replicaset 
12 Aug 2022 02:33:20,896 ERROR   Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:33:20,896 ERROR   Error resolving chart dependencies: Exception rendering template for mongodb-replicaset:3.17.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:33:20,896 ERROR   Chart mongodb-replicaset:3.17.0 failed to print even with the refresh option.
12 Aug 2022 02:34:11,256 ERROR   Error: template: mysqldump/templates/configmap.yaml:49:10: executing "mysqldump/templates/configmap.yaml" at <(.Values.persistence.enabled) or (.Values.persistentVolumeClaim)>: can't give argument to non-function .Values.persistence.enabled
12 Aug 2022 02:34:11,256 ERROR   
12 Aug 2022 02:34:11,256 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:34:11,256 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:34:11,256 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mysqldump 
12 Aug 2022 02:34:11,256 ERROR   Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:34:11,257 ERROR   Error resolving chart dependencies: Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:34:12,429 ERROR   Error: template: mysqldump/templates/configmap.yaml:49:10: executing "mysqldump/templates/configmap.yaml" at <(.Values.persistence.enabled) or (.Values.persistentVolumeClaim)>: can't give argument to non-function .Values.persistence.enabled
12 Aug 2022 02:34:12,429 ERROR   
12 Aug 2022 02:34:12,429 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:34:12,429 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:34:12,429 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template mysqldump 
12 Aug 2022 02:34:12,429 ERROR   Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:34:12,429 ERROR   Error resolving chart dependencies: Exception rendering template for mysqldump:2.6.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:34:12,429 ERROR   Chart mysqldump:2.6.0 failed to print even with the refresh option.
12 Aug 2022 02:39:11,649 ERROR   Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

12 Aug 2022 02:39:11,649 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

12 Aug 2022 02:39:12,854 ERROR   Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

12 Aug 2022 02:39:12,854 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.3 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

12 Aug 2022 02:39:12,854 ERROR   Chart pgadmin:1.2.3 failed to print even with the refresh option.
12 Aug 2022 02:39:13,985 ERROR   Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

12 Aug 2022 02:39:13,985 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

12 Aug 2022 02:39:15,163 ERROR   Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

12 Aug 2022 02:39:15,163 ERROR   Error resolving chart dependencies: Exception rendering template for pgadmin:1.2.2 : Can't construct a java object for tag:yaml.org,2002:string; exception=Class not found: string
 in 'reader', line 118, column 22:
                  value: !!string False
                         ^

12 Aug 2022 02:39:15,163 ERROR   Chart pgadmin:1.2.2 failed to print even with the refresh option.
12 Aug 2022 02:46:15,262 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.2.puml
12 Aug 2022 02:46:19,139 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.1.puml
12 Aug 2022 02:46:22,599 ERROR   Error in net.sourceforge.plantuml.GeneratedImage trying to generate image from /home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable//home/runner/work/helm-chartmap-generator/helm-chartmap-generator/docs/charts.helm.sh-stable/satisfy-1.1.0.puml
12 Aug 2022 02:48:10,917 ERROR   WARNING: This chart is deprecated
12 Aug 2022 02:48:10,917 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
12 Aug 2022 02:48:10,917 ERROR   
12 Aug 2022 02:48:10,917 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:48:10,917 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:48:10,917 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
12 Aug 2022 02:48:10,917 ERROR   Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:10,917 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:12,040 ERROR   WARNING: This chart is deprecated
12 Aug 2022 02:48:12,040 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
12 Aug 2022 02:48:12,040 ERROR   
12 Aug 2022 02:48:12,040 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:48:12,040 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:48:12,040 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
12 Aug 2022 02:48:12,040 ERROR   Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:12,040 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:12,040 ERROR   Chart signalsciences:2.0.2 failed to print even with the refresh option.
12 Aug 2022 02:48:13,155 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
12 Aug 2022 02:48:13,155 ERROR   
12 Aug 2022 02:48:13,155 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:48:13,155 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:48:13,155 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
12 Aug 2022 02:48:13,155 ERROR   Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:13,155 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:14,315 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
12 Aug 2022 02:48:14,315 ERROR   
12 Aug 2022 02:48:14,315 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:48:14,315 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:48:14,316 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
12 Aug 2022 02:48:14,316 ERROR   Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:14,316 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.1 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:14,316 ERROR   Chart signalsciences:2.0.1 failed to print even with the refresh option.
12 Aug 2022 02:48:15,411 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
12 Aug 2022 02:48:15,411 ERROR   
12 Aug 2022 02:48:15,411 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:48:15,411 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:48:15,411 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
12 Aug 2022 02:48:15,411 ERROR   Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:15,411 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:16,537 ERROR   Error: template: signalsciences/templates/NOTES.txt:1:12: executing "signalsciences/templates/NOTES.txt" at <(or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)) (or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.secretAccessKey))>: can't give argument to non-function or (.Values.signalsciences.accessKeyIdExistingSecret) (.Values.signalsciences.accessKeyId)
12 Aug 2022 02:48:16,537 ERROR   
12 Aug 2022 02:48:16,537 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:48:16,537 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:48:16,537 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template signalsciences 
12 Aug 2022 02:48:16,537 ERROR   Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:16,537 ERROR   Error resolving chart dependencies: Exception rendering template for signalsciences:2.0.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:48:16,538 ERROR   Chart signalsciences:2.0.0 failed to print even with the refresh option.
12 Aug 2022 02:49:21,923 ERROR   WARNING: This chart is deprecated
12 Aug 2022 02:49:21,923 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
12 Aug 2022 02:49:21,923 ERROR   
12 Aug 2022 02:49:21,923 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:49:21,923 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:49:21,923 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
12 Aug 2022 02:49:21,923 ERROR   Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
12 Aug 2022 02:49:21,923 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
12 Aug 2022 02:49:34,495 ERROR   WARNING: This chart is deprecated
12 Aug 2022 02:49:34,496 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
12 Aug 2022 02:49:34,496 ERROR   
12 Aug 2022 02:49:34,496 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:49:34,496 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:49:34,496 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
12 Aug 2022 02:49:34,496 ERROR   Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
12 Aug 2022 02:49:34,496 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.6 : Error running template command. Exit Value = 1.
12 Aug 2022 02:49:34,496 ERROR   Chart spinnaker:2.2.6 failed to print even with the refresh option.
12 Aug 2022 02:49:35,803 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
12 Aug 2022 02:49:35,803 ERROR   
12 Aug 2022 02:49:35,803 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:49:35,803 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:49:35,803 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
12 Aug 2022 02:49:35,803 ERROR   Exception rendering template for spinnaker:2.2.3 : Error running template command. Exit Value = 1.
12 Aug 2022 02:49:35,803 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.3 : Error running template command. Exit Value = 1.
12 Aug 2022 02:49:39,237 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.2255617797772069558/spinnaker. Exit code: 1. Possibly you cannot access one of your remote charts repos.
12 Aug 2022 02:49:39,237 ERROR   Chart spinnaker:2.2.3 failed to print even with the refresh option.
12 Aug 2022 02:49:40,599 ERROR   Error: template: spinnaker/charts/minio/templates/deployment.yaml:210:20: executing "spinnaker/charts/minio/templates/deployment.yaml" at <(not .Values.gcsgateway.enabled) (not .Values.azuregateway.enabled) (not .Values.s3gateway.enabled) (not .Values.b2gateway.enabled)>: can't give argument to non-function not .Values.gcsgateway.enabled
12 Aug 2022 02:49:40,599 ERROR   
12 Aug 2022 02:49:40,599 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:49:40,599 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:49:40,599 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template spinnaker 
12 Aug 2022 02:49:40,599 ERROR   Exception rendering template for spinnaker:2.2.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:49:40,599 ERROR   Error resolving chart dependencies: Exception rendering template for spinnaker:2.2.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:49:44,114 ERROR   Error resolving chart dependencies: Exception updating chart repo in directory /tmp/com.melahn.util.helm.ChartMap.Temporary.8631445887806797137/spinnaker. Exit code: 1. Possibly you cannot access one of your remote charts repos.
12 Aug 2022 02:49:44,115 ERROR   Chart spinnaker:2.2.2 failed to print even with the refresh option.
12 Aug 2022 02:51:18,071 ERROR   WARNING: This chart is deprecated
12 Aug 2022 02:51:18,071 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
12 Aug 2022 02:51:18,071 ERROR   
12 Aug 2022 02:51:18,072 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:51:18,072 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:51:18,072 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
12 Aug 2022 02:51:18,072 ERROR   Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:18,072 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:19,234 ERROR   WARNING: This chart is deprecated
12 Aug 2022 02:51:19,234 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
12 Aug 2022 02:51:19,234 ERROR   
12 Aug 2022 02:51:19,234 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:51:19,234 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:51:19,234 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
12 Aug 2022 02:51:19,234 ERROR   Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:19,234 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.2 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:19,235 ERROR   Chart sumokube:1.0.2 failed to print even with the refresh option.
12 Aug 2022 02:51:20,366 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
12 Aug 2022 02:51:20,366 ERROR   
12 Aug 2022 02:51:20,366 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:51:20,366 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:51:20,366 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
12 Aug 2022 02:51:20,366 ERROR   Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:20,366 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:21,540 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
12 Aug 2022 02:51:21,540 ERROR   
12 Aug 2022 02:51:21,540 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:51:21,540 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:51:21,541 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
12 Aug 2022 02:51:21,541 ERROR   Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:21,541 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.1 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:21,541 ERROR   Chart sumokube:1.0.1 failed to print even with the refresh option.
12 Aug 2022 02:51:22,687 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
12 Aug 2022 02:51:22,687 ERROR   
12 Aug 2022 02:51:22,687 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:51:22,687 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:51:22,687 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
12 Aug 2022 02:51:22,687 ERROR   Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:22,687 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:23,917 ERROR   Error: template: sumokube/templates/secrets.yaml:4:56: executing "sumokube/templates/secrets.yaml" at <.Release.Time.Seconds>: nil pointer evaluating interface {}.Seconds
12 Aug 2022 02:51:23,917 ERROR   
12 Aug 2022 02:51:23,917 ERROR   Use --debug flag to render out invalid YAML
12 Aug 2022 02:51:23,918 ERROR   Error running template command. Exit Value = 1.
12 Aug 2022 02:51:23,918 ERROR   ChartMapException Error running template command. Exit Value = 1. running template command: helm --set "alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-content\-services.alfresco\-digital\-workspace.enabled=true,alfresco\-content\-services.alfresco\-infrastructure.enabled=false,alfresco\-content\-services.externalHost=localhost-k8s,alfresco\-content\-services.networkpolicysetting.enabled=false,alfresco\-content\-services.repository.environment.IDENTITY_SERVICE_URI=http://localhost-k8s/auth,alfresco\-digital\-workspace.enabled=true,alfresco\-infrastructure.activemq.adminUser.username=foo,alfresco\-infrastructure.activemq.adminUser.Password=bar,alfresco\-infrastructure.alfresco\-api\-gateway.enabled=false,alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-infrastructure.alfresco\-activiti\-cloud\-registry.enabled=false,alfresco\-infrastructure.nginx\-ingress.enabled=true,alfresco\-process\-services.alfresco\-infrastructure.enabled=false,alfresco\-process\-services.alfresco\-infrastructure.alfresco\-api\-gateway.keycloakURL=http://localhost-k8s/auth,alfresco\-process\-services.processEngine.environment.IDENTITY_SERVICE_AUTH=http://localhost-k8s/auth,alfresco\-sync\-service.syncservice.enabled=true,azuregateway.enabled=false,b2gateway.enabled=false,global.service.name=foo-name,global.tracking.auth=secret,global.tracking.sharedsecret=foo-secret,global.keycloak.clientSecret=foo-secret,gcsgateway.enabled=true,ingress.enabled=false,ingress.domain=foo-domain,insightzeppelin.enabled=true,insightKey=foo-key,insightCrt=foo-crt,jfmcCrt=foo,jfmcKeystore=foo,postgresql\-syncservice.enabled=true,keycloakURL=http://localhost-k8s/auth,keycloak.persistence.dbVendor=postgres,keycloak.persistence.deployPostgres=true,mongodb.db.adminPassword=foo-password,mongodb.db.mcPassword=foo-password,mongodb.db.insightPassword=foo-password,mongodb.mongodbDatabase=foo,mongodb.mongodbPassword=foo-password,mongodb.mongodbRootPassword=foo-password,mongodb.mongodbUsername=foo-username,mongodb.uri=http://foo-uri,redis.redisPassword=foo-password,replicationPassword=foo-password,s3gateway.enabled=true,service.type=foo,service.port.number=9999,signalsciences.accessKeyId=foo-key,signalsciences.accessKeyIdExistingSecret=foo-secret,superuserPassword=foo-password"  template sumokube 
12 Aug 2022 02:51:23,918 ERROR   Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:23,918 ERROR   Error resolving chart dependencies: Exception rendering template for sumokube:1.0.0 : Error running template command. Exit Value = 1.
12 Aug 2022 02:51:23,918 ERROR   Chart sumokube:1.0.0 failed to print even with the refresh option.
